# Generated by Django 5.2.8 on 2025-11-26 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos_extras/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outras_imagens', to='app.produto')),
            ],
        ),
    ]
